- packages/GA4Client/src/initialization.js
- packages/GA4Server/src/GoogleAnalytics4EventForwarderServerSide.js
We are renaming `GoogleAnalytics4EventForwarder` to `GoogleAnalytics4`.
> chore: update forwarder name

- packages/GA4Client/src/common.js
If `None` is selected as the external identity type, there will still be console.warn showing `External identity type of None not set on the user`.  This is misleading and looks like an error.  We move this code into the above if block to correct this.
> fix: remove warning when external ID of None is selected

- packages/GA4Client/package.json
When we wan't to use the package we have an import error on compile.
After check we see the package.json was not update with the latest name file.
> Fix import filename with GA4 filename instead of old GA kit filename

- packages/GA4Client/src/event-handler.js
- packages/GA4Client/test/index.html
- packages/GA4Client/test/tests.js
- Adding Event Attributes to Page View Events so they behave more consistent with other events and user expectations.
- Manual and Automated Tests
- Closes https://go.mparticle.com/work/SQDSDKS-4554
> fix: Add Event Attributes to Pageview Event

- packages/GA4Client/src/event-handler.js
- packages/GA4Client/test/src/tests.js
Updaing the custom flags for `page` and `location` to be `GA4.Page` and `GA4.Location`.  We are keeping backwards compatibility in case any customers migrated to GA4 and kept their legacy GA implementation, which used `Google.Location` and `Google.Page`.
* Unit tests
* Manually saw in the Google UI that custom flags are working, page and location both sent in chrome network tab.
Closes https://go.mparticle.com/work/SQDSDKS-4966
> fix: Correct custom flags for title and location

- packages/GA4Client/src/common.js
- packages/GA4Client/test/src/tests.js
- If event attributes are set to `null`, the kit will throw an exception. We should be defensive and check to make sure the attributes are not actually empty or set to `null`.
- Run automated tests and use sample app to verify
Closes https://go.mparticle.com/work/SQDSDKS-5063
> fix: Check if Event Attributes are empty before truncating

- packages/GA4Client/package-lock.json
- packages/GA4Client/package.json
- packages/GA4Client/src/initialization.js
- packages/GA4Client/test/index.html
- packages/GA4Client/test/src/tests.js
- Capture measurement id on GA4 Client package and send to dataLayer as `client_id`.
- Manually test using sample app set for GA4 Client implementation
- Verify dataLayer contains `['get', 'testMeasurementId', 'client_id']` after init.
- Verify measurement ID is in `mParticle._Store.integrationAttributes`.
Closes https://go.mparticle.com/work/SQDSDKS-5415
> feat: Capture Client ID on Client Side Forwarding

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/src/initialization.js
- packages/GA4Client/test/src/tests.js
Custom Product Attributes should be on the same level as standard product attributes (price, quantity, etc).  CUrrent bug shows the attributes being sent as `[object Object]`.  
Added unit tests and sent tests in a test app and below screenshots show that the payload goes from showing `[object Object]` to the actual product attributes when sending an ecommerce event with the following product attributes:
```
var prodattr1 = {journeyType: 'testjourneytype1', eventMetric1: 'metric2'}
var prodattr2 = {'hit-att2': 'hit-att2-type', prodMetric1: 'metric1'}
var product1 = mParticle.eCommerce.createProduct('iphone', 'iphoneSKU', 999, 1, 'variant', 'category', 'brand', 1, 'coupon', prodattr1);
var product2 = mParticle.eCommerce.createProduct('galaxy', 'galaxySKU', 799, 1, 'variant', 'category', …
```
> fix: Flatten product.Attributes to be on the product level

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/test/src/tests.js
Add functionality to limit parameters for eCommerce events to 100 also.
Add unit test.  Send in a payload which has 101 keys, from `aa`, `ab`, `ac`, etc all the way to `dw`. `dw` is the 101st key, which gets removed from the payload when sending.  See screenshot below:
Closes https://go.mparticle.com/work/SQDSDKS-5733
> feat: Implement max parameters for eCommerce events

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/src/common.js
- packages/GA4Client/test/src/tests.js
Limit item parameters to 10 non-reserved keys.  Customers can have up to 10 keys in addition to `item_category2/3/4/5`. 
Unit tests added.  Screenshot shows a product being sent with item attributes that include `a`-`k`, along with an `item_category2`.  The payload shows that these are sent as `k0a`, `k1b`, `k2c`...all the way to `k9j` (thus dropping `k`, the 11th parameter alphabetically), and also includes `item_category2` sent as `c2` in the payload.  
Closes https://go.mparticle.com/work/SQDSDKS-5731
> feat: Limit item params to 10 non-reserved keys

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/test/src/tests.js
We were mapping product item coupons to `coupon_code` instead of `coupon` which GA4 has a reserved attribute for.
1.  Fixed unit tests where `CouponCode` was being mapped to `coupon_code`.  
2.  Tested in local test app, 1st screenshot shows payload with bug, where `coupon_code` is passed as a non-reserved keyword as `k0coupon_code~v0coupon123123`.  2nd screenshot shows fixed payload where `coupon` is sent as the reserved keyword, which GA4's SDK sends as `cpcoupon123123` differently.
Screenshot1
Screenshot2
Closes https://go.mparticle.com/work/SQDSDKS-5640
> fix: Map CouponCode to reserved attributes `coupon` instead of `coupon_code`

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/test/src/tests.js
`affiliation` is supposed to be item level and not event level as we currently have it.  There are lots of small code edits in this PR because each commerce action has its own `build` step, and almost all build steps also call the `buildProductsList` function (which now needs the affiliation).  
DRY-ing this up would have been a larger ticket, and I started down that path, but there began to be some significant code changes which are out of the scope of this ticket.  We can DRY it up per this sustained engineering ticket - https://mparticle-eng.atlassian.net/browse/SQDSDKS-5716
Fixed all unit tests where affiliation was at the event level.  Added a unit test to test a product with and without `affiliation` as a product attribute, and the behavior if there is an event level attribute.  The …
> fix: Re-map affiliation from event level to item level

- packages/GA4Client/src/common.js
- packages/GA4Client/test/src/tests.js
In my testing, I found that cleansing for attributes was still being done even if data cleansing was false.  It looks like these lines related to regex-ing the attribute name was not removed https://github.com/mparticle-integrations/mparticle-javascript-integration-google-analytics-4/pull/36/files#diff-2d099ec65653b8719574234ce177bf327823ed04ed4935d0483643596e1f50f6R49-R53
Added a unit test to ensure attribute is not cleansed if enable data cleansing is off.
Closes https://go.mparticle.com/work/SQDSDKS-5752
> fix: Prevent attribute cleansing when data cleansing is disabled

- packages/GA4Client/src/common.js
- packages/GA4Client/src/initialization.js
- packages/GA4Client/test/src/tests.js
This PR allows a customer to pass a standardization callback for name that affects event name, custom attributes, and product attributes.
Added unit tests.  Tested locally. 
The callback I used was to remove the last letter of each string.
Screen shot 1 shows a transaction sent with product attributes and custom attributes. 
Note that `eventMetric1` gets shortened to `eventMetric` in the payload. `journeyType` --> `journeyTyp`, and `sale` --> `sal`.
Screenshot 2
Shows `name` --> `nam`, `abc` --> `ab`, and `def` --> `de`.
Closes https://go.mparticle.com/work/SQDSDKS-5641
> feat: Add Customer Configurable Standardization

- packages/GA4Client/src/common.js
- packages/GA4Client/src/consent.js
- packages/GA4Client/src/event-handler.js
- packages/GA4Client/src/initialization.js
- packages/GA4Client/test/src/tests.js
- Adds a check to initForwarder and processEvents so that if the consent state changes, we alert Google via their `gtag` as per their [Consent Mode Documention](https://developers.google.com/tag-platform/security/guides/consent)
- Set up Consent Mapping and Privacy Configuration via the mParticle UI
- Using our [Data Privacy Controls] instructions, toggle some of the mapped consent states via the developer console
- Verify that mapped events appear in `window.dataLayer` via browser developer console as updates with updated values
Closes https://go.mparticle.com/work/SQDSDKS-6155
Mirrors similar update to [Adwords](https://github.com/mparticle-integrations/mparticle-javascript-integration-adwords/pull/52)
> feat: Add support for Consent State

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/src/common.js
- packages/GA4Client/src/event-handler.js
- packages/GA4Client/test/src/tests.js
A customer with more than one GA4 kit connection reported an issue with events being forwarded to the other GA4 connections even though they had forwarding rules set in the UI. After further investigation, it seemed that the issue was due to us using the global gtag('event', '<event_name>', {<event_params>}); per google API docs [here](https://developers.google.com/tag-platform/gtagjs/reference#event). However, using this method will result in forwarding every event to every available Google instance with a measurement ID, wether it has been initialized by our integration or even outside of mParticle. Google does allow to include a measurement Id as part of the {<event_params>} to forward only to the specific GA4 instance associated with a specific measurement ID (the one that has been …
> fix: include measurement Id as event param

- packages/GA4Client/src/consent.js
- packages/GA4Client/test/src/tests.js
1. PR target branch should be against `development`
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml
While consent purposes can be inputted into the web sdk via any casing, the SDK will automatically lowercase them to prevent pseudo-duplicate consent purposes.  In the UI, these have a capital first letter, and the server sends them back with a capital first letter also.   To keep it all consistent, we should lowercase what comes back from the server.
I also added this comment in our onetrust kit so that future developers are aware - …
> fix: Set mapped consent name from server to lowercase

- packages/GA4Client/src/common.js
- packages/GA4Client/src/event-handler.js
- packages/GA4Client/test/src/tests.js
This PR covers a bug fix and a feature request:
- fix: Google has a couple of exceptions for some attributes/params max lengths such as page_title (300 chars), page_location (1000 chars), page_referrer (420 chars) (doc [here](https://support.google.com/analytics/answer/9267744?hl=en)) while we automatically truncate every attribute and custom flag to 100 chars, this resulted in an issue where the customer reported missing attribution on the Google Ads side due to this issue.
- feature request: GA4 has a special param page_referrer that is similar to page_title and page_location and the request here is to include it as a custom flag to map into it. I included the new flag `GA4.Referrer` for the mapping. This flag has no legacy backwards compatibility as it wasn't available for GA Universal …
> fix: exceptional max attribute length and page_referrer flag addition

- packages/GA4Client/src/commerce-handler.js
- packages/GA4Client/test/src/tests.js
same issue as this [PR](https://github.com/mparticle-integrations/mparticle-android-integration-google-analytics-firebase-ga4/pull/90) for the Android, where custom attributes for both impression and promotion events don't forward. Right now the only kit that forwards them is the iOS GA4 Firebase kit
- Unit testing included and passed
- E2E testing with local overrides showed attributes in GA4 dashboard
Closes https://mparticle-eng.atlassian.net/browse/PRODRDMP-7123
> fix: forward Impressions and Promotions custom attributes

- packages/GA4Client/src/common.js
- packages/GA4Client/src/consent.js
- packages/GA4Client/src/event-handler.js
- packages/GA4Client/src/initialization.js
- packages/GA4Client/test/src/tests.js
- Same summary as this [PR](https://github.com/mparticle-integrations/mparticle-javascript-integration-google-tag-manager/pull/51) we had for the GTM kit
- [Y] Was this tested locally? If not, explain why.
- Tested E2E locally with overrides as well as unit tested
Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-6815
> fix: send default and update consent payloads on kit init
